"""
Debrief generator – produces structured input for the LLM debrief.

The debrief itself is generated by the LLM (see ``llm/interface.py``),
but this module assembles the deterministic, factual payload that the
LLM must use as its source of truth.
"""

from __future__ import annotations

from typing import Dict, List

from .state import ScenarioState
from .scoring import ScoringEngine


class DebriefGenerator:
    """Assemble debrief input from engine state + scores."""

    def __init__(
        self,
        protocol: dict,
        state: ScenarioState,
        scoring: ScoringEngine,
    ) -> None:
        self.protocol = protocol
        self.state = state
        self.scoring = scoring
        self._step_index = {s["id"]: s for s in protocol["steps"]}

    def generate_input(self) -> dict:
        """
        Return the structured debrief payload.  The LLM will use this
        (plus RAG chunks) to write the natural-language debrief.
        """
        completed = set(self.state.progress.completed_steps)
        all_steps = [s["id"] for s in self.protocol["steps"]]

        # Steps the trainee should have done but didn't
        # (based on the path that was active)
        missed = self._compute_missed_steps(completed)

        # Critical errors
        critical_errors = [
            v
            for v in self.state.progress.violations
            if v.get("critical")
        ]

        # Scores
        score_data = self.scoring.compute()

        # Steps done correctly (in order)
        correct_actions = [
            a["action"]
            for a in self.state.progress.actions_taken
            if a["result"].get("validity") == "valid"
        ]

        # Steps done incorrectly
        incorrect_actions = [
            {
                "action": a["action"],
                "reason": a["result"].get("reason", ""),
            }
            for a in self.state.progress.actions_taken
            if a["result"].get("validity") == "invalid"
        ]

        # Collect related step IDs for RAG retrieval
        rag_step_ids = list(
            set(missed)
            | {e.get("action", "") for e in critical_errors}
            | set(correct_actions)
        )

        return {
            "scenario_name": self.state.scenario_name,
            "difficulty": self.state.difficulty,
            "completed_steps": [
                {
                    "id": s,
                    "description": self._step_index.get(s, {}).get(
                        "description", s
                    ),
                }
                for s in correct_actions
            ],
            "missed_steps": [
                {
                    "id": s,
                    "description": self._step_index.get(s, {}).get(
                        "description", s
                    ),
                    "critical": self._step_index.get(s, {}).get(
                        "critical", False
                    ),
                }
                for s in missed
            ],
            "incorrect_actions": incorrect_actions,
            "critical_errors": [
                {
                    "action": e.get("action", ""),
                    "type": e.get("type", ""),
                    "constraint": e.get("constraint", ""),
                }
                for e in critical_errors
            ],
            "scores": score_data["scores"],
            "penalties": score_data["penalties"],
            "total_actions": len(self.state.progress.actions_taken),
            "hint_requests": self.state.progress.hint_requests,
            "rag_step_ids": rag_step_ids,
        }

    # ── Internals ──────────────────────────────────────────────────────────

    def _compute_missed_steps(self, completed: set) -> List[str]:
        """
        Walk the protocol graph along the path that *should* have been
        taken (given the scenario state) and return steps not completed.
        """
        missed: List[str] = []
        visited: set[str] = set()
        current = self.protocol.get("initial_step")

        while current and current not in visited:
            visited.add(current)
            step = self._step_index.get(current)
            if step is None:
                break

            if current not in completed:
                missed.append(current)

            # Determine next step
            if step.get("type") == "decision":
                # Pick the branch based on current state
                next_step = None
                state = self.state.get_state()
                for cond in step.get("conditions", []):
                    parts = cond["if"].strip().split()
                    if len(parts) == 3:
                        var, op, val = parts
                        if val.lower() == "true":
                            val = True
                        elif val.lower() == "false":
                            val = False
                        actual = state.get(var)
                        if (op == "==" and actual == val) or (
                            op == "!=" and actual != val
                        ):
                            next_step = cond["next"]
                            break
                if next_step is None and step.get("conditions"):
                    next_step = step["conditions"][0]["next"]
                current = next_step
            elif step.get("terminal"):
                break
            elif step.get("allowed_next"):
                current = step["allowed_next"][0]
            else:
                break

        return missed
